# Harvesting
# Data is recorded from September - April
start: "2010-09-20T00:00:00Z"
end: "2011-09-21T00:00:00Z"

<<<<<<< HEAD
# Provide date format from filename
regex: '\d{8}'
=======
start: "19990101T00:00:00Z"
end: "19990104T23:59:59Z"
user: anonymous
host: sidads.colorado.edu
>>>>>>> 81a6f9bbc7c057003d76d2e80e67873db5dd2713
date_regex: "%Y-%m-%dT%H:%M:%SZ"

# Dataset
ds_name: seaice_RDEFT4
<<<<<<< HEAD
aggregated: false
short_name: seaice_RDEFT4
data_time_scale: monthly
=======
ddir: pub/DATASETS/NOAA/RDEFT4/
aggregated: false
short_name: seaice_conc_daily_icdr_G02202
data_time_scale: daily
>>>>>>> 81a6f9bbc7c057003d76d2e80e67873db5dd2713
date_format: yyyymmdd
regions: []
fields:
  [
    {
      name: sea_ice_thickness,
      long_name: Sea ice thickness,
      standard_name: ' ',
      units: Meters,
    },
    {
      name: snow_depth,
      long_name: Snow depth,
      standard_name: " ",
      units: Meters
    },
    {
      name: freeboard,
      long_name: Ice freeboard,
      standard_name: " ",
      units: Meters
    }
  ]
# new_data_attrs:
original_dataset_title: CryoSat-2 Level-4 Sea Ice Elevation, Freeboard, and Thickness, Version 1
original_dataset_short_name: seaice_RDEFT4
original_dataset_url: https://nsidc.org/data/RDEFT4
original_dataset_reference: https://doi.org/10.5067/96JO0KIFDAS8
original_dataset_doi: 10.5067/96JO0KIFDAS8

# Local
# REMEMBER, REPLACE LOCAL PATHS SO THEY POINT TO YOUR /SRC/ DIRECTORY
solr_host: http://localhost:8983/solr/
solr_collection_name: ecco_datasets
target_dir: /Users/kevinmarlis/Developer/JPL/ecco-preprocessing/src/harvesters/seaice_harvester/harvested_granule/SEAICE_CONC_RDEFT4
# AWS
# target_bucket_name: ecco-preprocess
