# Run the following command from Sea-Level-Indicators to install all necessary packages
# in a conda environment called sli-pipeline

# conda env create -f SLI-pipeline/src/tools/package.yaml -n sli-pipeline

name: sli-pipeline

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.7.7
  - pyresample=1.15.0
  - numpy=1.18.1
  - pyyaml=5.3.1
  - netcdf4=1.5.3
  - python-dateutil=2.8.1
  - requests=2.23.0
  - xarray=0.16.2
