# Harvesting

# PODAAC explicitely expects this date format
start: "20160101T00:00:01Z"
end: "20161231T23:59:59Z"
user: anonymous
host: https://podaac.jpl.nasa.gov/ws/search/granule/?format=atom&pretty=false&itemsPerPage=300000
date_regex: "%Y-%m-%dT%H:%M:%SZ"

# Dataset
ds_name: sss_SMAP
podaac_id: PODAAC-SMP40-3SMCS
aggregated: false
short_name: SMAP_RSS_L3_SSS_SMI_MONTHLY_V4
data_time_scale: monthly
date_format: yyyy_mm
fields:
  [
    {
      name: sss_smap_40km,
      long_name: SMAP sea surface salinity,
      standard_name: sea_surface_salinity,
      units: 1e-3,
    },
    {
      name: sss_smap_uncertainty,
      long_name: estimated empirical uncertainty of SMAP sea surface salinity smoothed to approx 70km resolution,
      standard_name: " ",
      units: 1e-3,
    },
  ]
# new_data_attrs:
original_dataset_title: RSS SMAP Level 3 Sea Surface Salinity Standard Mapped Image Monthly V4.0 Validated Dataset
original_dataset_short_name: SMAP_RSS_L3_SSS_SMI_MONTHLY_V4
original_dataset_url: https://podaac.jpl.nasa.gov/dataset/SMAP_RSS_L3_SSS_SMI_MONTHLY_V4
original_dataset_reference: http://smap.jpl.nasa.gov/
original_dataset_doi: 10.5067/SMP40-3SMCS

# Local
# REMEMBER, REPLACE LOCAL PATHS SO THEY POINT TO YOUR /SRC/ DIRECTORY
solr_host: http://localhost:8983/solr/
solr_collection_name: ecco_datasets
target_dir: /Users/kevinmarlis/Developer/JPL/ecco-preprocessing/src/harvesters/podaac_harvester/harvested_granule/SSS_SMAP_MONTHLY
# AWS
# target_bucket_name: ecco-preprocess
