# =====================================================
# PODAAC
# =====================================================
# PODAAC explicitly expects this date format
start: "" # yyyymmddThh:mm:ssZ
end: "" # yyyymmddThh:mm:ssZ
most_recent: True # Overrides end date to be current date at time of execution
name: ""
password: ""
# host: https://podaac.jpl.nasa.gov/ws/search/granule/?format=atom&pretty=false&itemsPerPage=300000 # does not change
date_regex: "%Y-%m-%dT%H:%M:%SZ" # does not change

# =====================================================
# Dataset
# =====================================================
ds_name: "" # Name for dataset
harvester_type: "local"
podaac_id: ""

# new_data_attrs:
original_dataset_title: ""
original_dataset_short_name: ""
original_dataset_url: ""
original_dataset_reference: ""
original_dataset_doi: ""

# =====================================================
# Solr
# =====================================================
solr_host_local: http://localhost:8983/solr/ # doesn't change if following standard Solr setup
solr_collection_name: sealevel_datasets # doesn't change
