# Local Directories
mapping_factors_dir: '/home/bark/ECCO_GROUP/ECCO-ACCESS/generating_netcdf/V1_cloud/mapping_factors'
diags_root: '/home/bark/ECCO_GROUP/ECCO-ACCESS/generating_netcdf/V1_cloud/temp_data'
metadata_json_dir: '/home/bark/ECCO_GROUP/ECCO-ACCESS/metadata/ECCOv4r4_metadata_json'
podaac_dir: '/home/bark/ECCO_GROUP/ECCO-ACCESS/generating_netcdf/V1_cloud/podaac'
ecco_grid_dir: '/home/bark/ECCO_GROUP/ECCO-ACCESS/generating_netcdf/V1_cloud/ecco_grids'
ecco_grid_dir_mds: '/home/bark/ECCO_GROUP/ECCO-ACCESS/generating_netcdf/V1_cloud/ecco_grids'

# ECCO Grid filename
ecco_grid_filename: 'ECCO_V4r4_llc90_grid_geometry.nc'

# Command line arguments (must include either these, or the actual command line arguments)
time_steps_to_process: ''
grouping_to_process: ''
product_type: ''
output_freq_code: ''
output_dir: '.'