# Dataset
ds_name: seaice_RDEFT4
version: 1.0
array_precision: float32
time_zone_included_with_time: False
extra_information: ['no_time']
data_res: 25/111
data_max_lat: 90.0
area_extent: [-3850000, -5350000, 3750000, 5850000]
dims: [304,448]
proj_info:
  {'area_id':'3411',
   'area_name':'polar_stereographic',
   'proj_id':'3411',
   'proj4_args':'+init=EPSG:3411'} 

extra_transformation_steps: []

# Local
# REMEMBER, REPLACE LOCAL PATHS SO THEY POINT TO YOUR /SRC/ DIRECTORY
solr_host: http://localhost:8983/solr/
solr_collection_name: ecco_datasets
output_dir: /Users/kevinmarlis/Developer/JPL/ecco-preprocessing/src/output/
# AWS
# solr_host: http://ec2-3-16-187-19.us-east-2.compute.amazonaws.com:8983/solr/
# solr_collection_name: ecco_datasets
# source_bucket: ecco-preprocess
# target_bucket: ecco-ames
# aws_output_dir: sst_AVHRR_transformed/
# aws_lon_grid_path: ECCO_grid_blank_model/XC.data
# aws_lat_grid_path: ECCO_grid_blank_model/YC.data
