# Harvesting

start: "19990101T00:00:00Z"
end: "19990104T23:59:59Z"

user: anonymous
host: sidads.colorado.edu
date_regex: "%Y-%m-%dT%H:%M:%SZ"

# Dataset
ds_name: seaice_G02202
ddir: pub/DATASETS/NOAA/G02202_V3/
aggregated: false
short_name: seaice_conc_daily_icdr_G02202
data_time_scale: daily
date_format: yyyymmdd
regions: ['north', 'south']
fields:
  [
    {
      name: seaice_conc_cdr,
      long_name: NOAA/NSIDC Climate Data Record of Passive Microwave Daily Sea Ice Concentration,
      standard_name: sea_ice_area_fraction,
      units: 1,
    },
    {
      name: stdev_of_seaice_conc_cdr,
      long_name: Passive Microwave Daily Northern Hemisphere Sea Ice Concentration Source Estimated Standard Deviation,
      standard_name: " ",
      units: " "
    }
  ]
# new_data_attrs:
original_dataset_title: NOAA/NSIDC Climate Data Record of Passive Microwave Sea Ice Concentration, Version 3
original_dataset_short_name: seaice_conc_daily_icdr_G02202
original_dataset_url: https://nsidc.org/data/G02202/versions/3
original_dataset_reference: https://nsidc.org/sites/nsidc.org/files/technical-references/SeaIce_CDR_CATBD_final_Rev-7.pdf
original_dataset_doi: 10.7265/N59P2ZTG

# Local
# REMEMBER, REPLACE LOCAL PATHS SO THEY POINT TO YOUR /SRC/ DIRECTORY
solr_host: http://localhost:8983/solr/
solr_collection_name: ecco_datasets
target_dir: /Users/kevinmarlis/Developer/JPL/ecco-preprocessing/src/harvesters/seaice_harvester/harvested_granule/SEAICE_CONC_G02202_DAILY
# AWS
# target_bucket_name: ecco-preprocess
