# Local Directories
# =================================================================================================
# Directory to look for/download mapping factors
# mapping_factors_dir: '/home/bark/ecco_repos/ECCO_GROUP/ECCO-ACCESS/generating_netcdf/V1_cloud/mapping_factors'
# mapping_factors_dir: '/Users/bark/Documents/ECCO_GROUP/ECCO-ACCESS/generating_netcdf/V1_cloud/mapping_factors'
mapping_factors_dir: ''

# Directory to look for all data. Should have sub folders for 'diags_monthly', 'diags_daily', and/or 'diags_inst'.
# Can be set to an S3 bucket address.
# model_data_dir: '/home/bark/ecco_repos/ECCO_GROUP/ECCO-ACCESS/generating_netcdf/V1_cloud/diags_all'
# model_data_dir: '/Users/bark/Documents/ECCO_GROUP/ECCO-ACCESS/generating_netcdf/V1_cloud/diags_all'
model_data_dir: ''

# ECCO-ACCESS metadata information
# metadata_json_dir: '/home/bark/ecco_repos/ECCO_GROUP/ECCO-ACCESS/metadata/ECCOv4r4_metadata_json'
# metadata_json_dir: '/Users/bark/Documents/ECCO_GROUP/ECCO-ACCESS/metadata/ECCOv4r4_metadata_json'
metadata_json_dir: ''

# Path to PODAAC metadata document
# podaac_dir: '/home/bark/ecco_repos/ECCO_GROUP/ECCO-ACCESS/metadata/ECCOv4r4_metadata_json/PODAAC_datasets-revised_20210226.5.csv'
# podaac_dir: '/Users/bark/Documents/ECCO_GROUP/ECCO-ACCESS/metadata/ECCOv4r4_metadata_json/PODAAC_datasets-revised_20210226.5.csv'
podaac_dir: ''

# Directory containing ECCO grids
# ecco_grid_dir: '/home/bark/ecco_repos/ECCO_GROUP/ECCO-ACCESS/generating_netcdf/V1_cloud/ecco_grids'
# ecco_grid_dir: '/Users/bark/Documents/ECCO_GROUP/ECCO-ACCESS/generating_netcdf/V1_cloud/ecco_grids'
ecco_grid_dir: ''

# Directory containing ECCO grids (to use for native product_type)
# ecco_grid_dir_mds: '/home/bark/ecco_repos/ECCO_GROUP/ECCO-ACCESS/generating_netcdf/V1_cloud/ecco_grids'
# ecco_grid_dir_mds: '/Users/bark/Documents/ECCO_GROUP/ECCO-ACCESS/generating_netcdf/V1_cloud/ecco_grids'
ecco_grid_dir_mds: ''

# ECCO Grid filename
# ecco_grid_filename: 'ECCO_V4r4_llc90_grid_geometry.nc'
ecco_grid_filename: 'GRID_GEOMETRY_ECCO_V4r4_native_llc0090.nc'

# Output directory string. Can be set to an S3 bucket address.
# output_dir: '/home/bark/ecco_repos/ECCO_GROUP/ECCO-ACCESS/generating_netcdf/V1_cloud/temp_output'
# output_dir: '/Users/bark/Documents/ECCO_GROUP/ECCO-ACCESS/generating_netcdf/V1_cloud/temp_output'
output_dir: ''

# GROUPINGS
# =================================================================================================
# 20 NATIVE GRID GROUPINGS
#    0 dynamic sea surface height and model sea level anomaly
#    1 ocean bottom pressure and model ocean bottom pressure anomaly
#    2 ocean and sea-ice surface freshwater fluxes
#    3 ocean and sea-ice surface heat fluxes
#    4 atmosphere surface temperature, humidity, wind, and pressure
#    5 ocean mixed layer depth
#    6 ocean and sea-ice surface stress
#    7 sea-ice and snow concentration and thickness
#    8 sea-ice velocity
#    9 sea-ice and snow horizontal volume fluxes
#    10 Gent-McWilliams ocean bolus transport streamfunction
#    11 ocean three-dimensional volume fluxes
#    12 ocean three-dimensional potential temperature fluxes
#    13 ocean three-dimensional salinity fluxes
#    14 sea-ice salt plume fluxes
#    15 ocean potential temperature and salinity
#    16 ocean density, stratification, and hydrostatic pressure
#    17 ocean velocity
#    18 Gent-McWilliams ocean bolus velocity
#    19 ocean three-dimensional momentum tendency

# ----- > groupings_native_snap (5) = [0, 1, 7, 8, 15]
# SSH, obp, sea ice and snow, sea ice velocity, TS

# 13 LATLON GRID GROUPINGS
#    0 dynamic sea surface height
#    1 ocean bottom pressure
#    2 ocean and sea-ice surface freshwater fluxes
#    3 ocean and sea-ice surface heat fluxes
#    4 atmosphere surface temperature, humidity, wind, and pressure
#    5 ocean mixed layer depth
#    6 ocean and sea-ice surface stress
#    7 sea-ice and snow concentration and thickness
#    8 sea-ice velocity
#    9 ocean potential temperature and salinity
#    10 ocean density, stratification, and hydrostatic pressure
#    11 ocean velocity
#    12 Gent-McWilliams ocean bolus velocity