# Local Setup
# =================================================================================================
# Directory to look for/download mapping factors
mapping_factors_dir: ''

# Directory to look for all data. Should have sub folders for 'diags_monthly', 'diags_daily', and/or 'diags_inst'.
model_data_dir: ''

# Output directory string.
output_dir: ''



# Cloud Setup
# =================================================================================================
# AWS Profile name
aws_profile_name: 'saml-pub'

# AWS region
aws_region: 'us-west-2'

# S3 bucket name for all data (leave blank if local, i.e. in the docker image).
model_granule_bucket: 'ecco-model-granules'

# Output S3 bucket name (leave blank if local, i.e. in the docker image)
processed_data_bucket: 'ecco-processed-data'



# Misc
# =================================================================================================
# All local vs Cloud
local: False



# GROUPINGS
# =================================================================================================
# 20 NATIVE GRID GROUPINGS
#    0 dynamic sea surface height and model sea level anomaly
#    1 ocean bottom pressure and model ocean bottom pressure anomaly
#    2 ocean and sea-ice surface freshwater fluxes
#    3 ocean and sea-ice surface heat fluxes
#    4 atmosphere surface temperature, humidity, wind, and pressure
#    5 ocean mixed layer depth
#    6 ocean and sea-ice surface stress
#    7 sea-ice and snow concentration and thickness
#    8 sea-ice velocity
#    9 sea-ice and snow horizontal volume fluxes
#    10 Gent-McWilliams ocean bolus transport streamfunction
#    11 ocean three-dimensional volume fluxes
#    12 ocean three-dimensional potential temperature fluxes
#    13 ocean three-dimensional salinity fluxes
#    14 sea-ice salt plume fluxes
#    15 ocean potential temperature and salinity
#    16 ocean density, stratification, and hydrostatic pressure
#    17 ocean velocity
#    18 Gent-McWilliams ocean bolus velocity
#    19 ocean three-dimensional momentum tendency

# ----- > groupings_native_snap (5) = [0, 1, 7, 8, 15]
# SSH, obp, sea ice and snow, sea ice velocity, TS

# 13 LATLON GRID GROUPINGS
#    0 dynamic sea surface height
#    1 ocean bottom pressure
#    2 ocean and sea-ice surface freshwater fluxes
#    3 ocean and sea-ice surface heat fluxes
#    4 atmosphere surface temperature, humidity, wind, and pressure
#    5 ocean mixed layer depth
#    6 ocean and sea-ice surface stress
#    7 sea-ice and snow concentration and thickness
#    8 sea-ice velocity
#    9 ocean potential temperature and salinity
#    10 ocean density, stratification, and hydrostatic pressure
#    11 ocean velocity
#    12 Gent-McWilliams ocean bolus velocity