# =====================================================
# PODAAC
# =====================================================
# PODAAC explicitly expects this date format
start: "" # yyyymmddThh:mm:ssZ
end: "" # yyyymmddThh:mm:ssZ
user: anonymous # does not change
host: https://podaac.jpl.nasa.gov/ws/search/granule/?format=atom&pretty=false&itemsPerPage=300000 # does not change
date_regex: "%Y-%m-%dT%H:%M:%SZ" # does not change

# =====================================================
# Dataset
# =====================================================
ds_name: "" # Name for dataset
podaac_id: ""
aggregated: false # if data is available aggregated
short_name: ""
data_time_scale: "" # daily or monthly
date_format: "" # format of date in file name ex: yyyymmdd
fields: [{ name: "", long_name: "", standard_name: "", units: "" }]

# new_data_attrs:
original_dataset_title: ""
original_dataset_short_name: ""
original_dataset_url: ""
original_dataset_reference: ""
original_dataset_doi: ""

# =====================================================
# Solr
# =====================================================
solr_host_local: http://localhost:8983/solr/ # doesn't change if following standard Solr setup
solr_host_aws: ""
solr_collection_name: ecco_datasets # doesn't change

# =====================================================
# Local
# =====================================================
# REMEMBER, REPLACE LOCAL PATHS SO THEY POINT TO YOUR /SRC/ DIRECTORY
target_dir: ../ecco-preprocessing/src/harvesters/podaac_harvester/harvested_granule/{ds_name}

# =====================================================
# AWS
# =====================================================
target_bucket_name: ecco-preprocess
