# =====================================================
# Seaice FTP
# =====================================================
start: "20180130T00:00:00Z" # yyyymmddThh:mm:ssZ
end: "20180202T00:00:00Z" # yyyymmddThh:mm:ssZ
user: anonymous # does not change
host: osisaf.met.no # does not change
regex: '\d{8}'
date_regex: "%Y-%m-%dT%H:%M:%SZ" # does not change

# =====================================================
# Dataset
# =====================================================
ds_name: "seaice_AMSR-2_OSI-408" # Name for dataset
harvester_type: "osisaf_ftp"
ddir: "archive/ice/conc_amsr/" #ex: archive/ice/conc/
filename_filter: "tud" # string to match for filenames to download ex: polstere-100_multi
aggregated: false # if data is available aggregated
data_time_scale: "daily" # daily or monthly
date_format: "yyyymmdd" # format of date in file name ex: yyyymmdd
regions: ['north', 'south'] # regions data is split into ex: ['north', 'south']
fields: [{ name: "ice_conc", long_name: "Sea ice concentration", standard_name: "sea_ice_area_fraction", units: "%" },
{ name: "confidence_level", long_name: "confidence level", standard_name: " ", units: " " }]

# new_data_attrs:
original_dataset_title: "Global Sea Ice Concentration (AMSR-2)"
original_dataset_short_name: "Global Sea Ice Concentration (AMSR-2)"
original_dataset_url: "http://www.osi-saf.org/?q=content/global-sea-ice-concentration-amsr-2"
original_dataset_reference: "https://osisaf-hl.met.no/sites/osisaf-hl.met.no/files/user_manuals/osisaf_cdop2_ss2_pum_amsr2-ice-conc_v1p1.pdf"
original_dataset_doi: "OSI-408"

# =====================================================
# Solr
# =====================================================
solr_host_local: http://localhost:8983/solr/ # doesn't change if following standard Solr setup
solr_host_aws: http://ec2-3-16-187-19.us-east-2.compute.amazonaws.com:8983/solr/
solr_collection_name: ecco_datasets # doesn't change

# =====================================================
# AWS
# =====================================================
target_bucket_name: ecco-preprocess
