# Harvesting

# PODAAC explicitely expects this date format
start: "19920101T00:00:01Z"
end: "19920105T23:59:59Z"
podaac_id: PODAAC-GHAAO-4BC02
user: anonymous
host: https://podaac.jpl.nasa.gov/ws/search/granule/?format=atom&pretty=false&itemsPerPage=300000
aggregated: false
# Provide date format from filename
regex: '\d{8}'
date_regex: "%Y-%m-%dT%H:%M:%SZ"

# Dataset
ds_name: sst_AVHRR
short_name: AVHRR_OI-NCEI-L4-GLOB-v2.0
data_time_scale: daily
date_format: yyyymmdd
fields:
  [
    {
      name: analysed_sst,
      long_name: analysed sea surface temperature,
      standard_name: sea_surface_temperature,
      units: kelvin,
    },
    {
      name: analysis_error,
      long_name: estimated error standard deviation of analysed_sst,
      standard_name: " ",
      units: kelvin,
    },
  ]
# new_data_attrs:
original_dataset_title: GHRSST Level 4 AVHRR_OI Global Blended Sea Surface Temperature Analysis (GDS version 2) from NCEI
original_dataset_short_name: AVHRR_OI-NCEI-L4-GLOB-v2.0
original_dataset_url: https://podaac.jpl.nasa.gov/dataset/AVHRR_OI-NCEI-L4-GLOB-v2.0
original_dataset_reference: http://www.earth-syst-sci-data.net/8/165/2016/
original_dataset_doi: 10.5067/GHAAO-4BC02

# Local
# REMEMBER, REPLACE LOCAL PATHS SO THEY POINT TO YOUR /SRC/ DIRECTORY
solr_host: http://localhost:8983/solr/
solr_collection_name: ecco_datasets
target_dir: /Users/kevinmarlis/Developer/JPL/ecco-preprocessing/src/harvesters/podaac_harvester/harvested_granule/SST_AVHRR_DAILY
# AWS
# target_bucket_name: ecco-preprocess
